### ISSUE TITLE
Browse button doesn't work in new release

### ISSUE THREAD

**Issue by yahu1031** [YazeedAlKhalaf/Flutter_Installer#16]
Browse button doesn't work on click. it makes the documents folder as default installation folder and can't change the path.

**Comment by YazeedAlKhalaf** [comment]
The bug is fixed in the `master` branch. I just didn't add the platform-specific packages. Will fix some other bugs and then release a new version.

Thanks for pointing out this bug @yahu1031

If you believe the bug still exists in the release `0.0.8` that will be released today reply so I can open the issue.

I feel safe to close this issue now! 🚀
